//
//  SecureEnclaveManager.swift
//  CoreInfrastructure
//
//  Created by Nicolas Bouème on 22/04/2026.
//

import CryptoKit
import Foundation

public struct SecureEnclaveManager: Sendable {
    public enum Failure: Error, Equatable, Sendable {
        case keychainError(OSStatus)
        case corruptedCiphertext
        case handleAlreadyExists
        case secureEnclaveUnavailable
        case unknown
    }

    private let keychainService: String
    private static let keychainAccount = "se-encryption-key"

    public init(
        keychainService: String = "com.ikaros.SolanaWallet"
    ) throws {
        guard SecureEnclave.isAvailable else {
            throw Failure.secureEnclaveUnavailable
        }
        self.keychainService = keychainService
    }

    public func encrypt(_ plaintext: Data) throws -> Data {
        let seKey = try loadOrCreateEncryptionKey()

        // On-memory key (Outside SecureEnclave)
        let ephemeral = P256.KeyAgreement.PrivateKey()

        // ECDH
        let shared = try ephemeral.sharedSecretFromKeyAgreement(with: seKey.publicKey)

        // HKDF
        let symKey = shared.hkdfDerivedSymmetricKey(
            using: SHA256.self,
            salt: Data(),
            sharedInfo: Self.hkdfInfo,
            outputByteCount: 32
        )

        // AES-GCM seal
        let sealed = try AES.GCM.seal(plaintext, using: symKey)
        guard let combined = sealed.combined else {
            throw Failure.unknown
        }

        // blob = public ephemeral ∥ (nonce ∥ ciphertext ∥ tag)
        return ephemeral.publicKey.rawRepresentation + combined
    }

    public func decrypt(_ ciphertext: Data) throws -> Data {
        let seKey = try loadOrCreateEncryptionKey()

        guard ciphertext.count >= Self.minimumCiphertextSize else {
            throw Failure.corruptedCiphertext
        }
        let ephemeralPubBytes = ciphertext.prefix(Self.ephemeralPublicKeySize)
        let sealedCombined = ciphertext.dropFirst(Self.ephemeralPublicKeySize)

        let ephemeralPub = try P256.KeyAgreement.PublicKey(
            rawRepresentation: ephemeralPubBytes
        )

        // ECDH
        let shared = try seKey.sharedSecretFromKeyAgreement(with: ephemeralPub)

        // HKDF
        let symKey = shared.hkdfDerivedSymmetricKey(
            using: SHA256.self,
            salt: Data(),
            sharedInfo: Self.hkdfInfo,
            outputByteCount: 32
        )

        // AES-GCM open
        let sealed = try AES.GCM.SealedBox(combined: sealedCombined)
        return try AES.GCM.open(sealed, using: symKey)
    }

    public func reset() throws {
        try deleteEncryptionKey()
    }

    // MARK: Private

    private static let hkdfInfo = Data("SolanaWallet.se-encryption.v1".utf8)
    private static let ephemeralPublicKeySize = 64
    private static let minimumCiphertextSize = ephemeralPublicKeySize + 12 + 16 // = 92
    private var baseQuery: [String: Any] {
        [
            kSecClass as String: kSecClassGenericPassword,
            kSecAttrService as String: keychainService,
            kSecAttrAccount as String: Self.keychainAccount
        ]
    }

    /// Returns the Secure Enclave encryption key handle, creating one on first use.
    ///
    /// Resolves the "load existing or generate new" step of every encrypt
    /// and decrypt call into a single handle. A fresh key is minted inside
    /// the Secure Enclave only when no handle is stored in the Keychain,
    /// so repeated calls are cheap after the first one.
    ///
    /// Safe under concurrent first-use: if two callers race past the
    /// initial lookup, the losing ``SecItemAdd`` surfaces
    /// ``Failure/handleAlreadyExists`` and is recovered by re-reading the
    /// winner's handle. The fresh key generated by the loser is discarded
    /// and its material is released by the Secure Enclave.
    ///
    /// - Returns: A usable Secure Enclave key handle for ECDH.
    /// - Throws: ``Failure/keychainError(_:)`` for unrecoverable Keychain
    ///   failures; ``Failure/unknown`` if the post-race lookup unexpectedly
    ///   finds no item; rethrows any error from key generation.
    private func loadOrCreateEncryptionKey() throws -> SecureEnclave.P256.KeyAgreement.PrivateKey {
        if let existing = try lookupEncryptionKey() {
            return existing
        }
        let fresh = try SecureEnclave.P256.KeyAgreement.PrivateKey()
        do {
            try storeEncryptionKey(fresh.dataRepresentation)
            return fresh
        } catch Failure.handleAlreadyExists {
            // race: someone wrote inside lookup and store
            guard let winner = try lookupEncryptionKey() else {
                throw Failure.unknown
            }
            return winner
        }
    }

    /// Loads the Secure Enclave encryption key handle from the Keychain, if present.
    ///
    /// Reads the opaque handle stored under this service/account pair and
    /// rehydrates it into a `SecureEnclave.P256.KeyAgreement.PrivateKey`.
    /// The rehydrated value is a reference to the key inside the Secure
    /// Enclave; the private material never reaches process memory.
    ///
    /// A missing item is an expected state (first launch, post-reset) and
    /// is reported as `nil` rather than an error so callers can branch on
    /// "create vs. load" without catching.
    ///
    /// - Returns: The existing key handle, or `nil` if none is stored.
    /// - Throws: ``Failure/keychainError(_:)`` for any Keychain failure
    ///   other than `errSecItemNotFound`; ``Failure/unknown`` if the
    ///   Keychain returns a value that is not `Data`.
    private func lookupEncryptionKey() throws -> SecureEnclave.P256.KeyAgreement.PrivateKey? {
        var query = baseQuery
        query[kSecReturnData as String] = true

        var result: CFTypeRef?
        let status = SecItemCopyMatching(query as CFDictionary, &result)

        switch status {
        case errSecSuccess:
            guard let data = result as? Data else {
                throw Failure.unknown
            }
            return try SecureEnclave.P256.KeyAgreement.PrivateKey(dataRepresentation: data)
        case errSecItemNotFound:
            return nil
        default:
            throw Failure.keychainError(status)
        }
    }

    /// Persists a Secure Enclave encryption key handle in the Keychain.
    ///
    /// Only the opaque handle (`dataRepresentation`) is written; the private
    /// key material never leaves the Secure Enclave. The item is stored with
    /// `kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly` so it cannot be
    /// restored to another device and is unavailable before the first
    /// post-boot unlock.
    ///
    /// Not idempotent: callers must ensure no handle is already stored for
    /// the same service/account pair. A concurrent write by another process
    /// or task is surfaced as ``Failure/handleAlreadyExists`` so the caller
    /// can recover by reloading the winning handle.
    ///
    /// - Parameter representation: The `dataRepresentation` of a
    ///   `SecureEnclave.P256.KeyAgreement.PrivateKey`.
    /// - Throws: ``Failure/handleAlreadyExists`` if an item already exists
    ///   at this service/account pair; ``Failure/keychainError(_:)`` for any
    ///   other Keychain failure.
    private func storeEncryptionKey(_ representation: Data) throws {
        var attributes = baseQuery
        attributes[kSecValueData as String] = representation
        attributes[kSecAttrAccessible as String] = kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly

        let status = SecItemAdd(attributes as CFDictionary, nil)
        switch status {
        case errSecSuccess:
            return
        case errSecDuplicateItem:
            throw Failure.handleAlreadyExists
        default:
            throw Failure.keychainError(status)
        }
    }

    /// Removes the Secure Enclave encryption key handle from the Keychain.
    ///
    /// The private key material held by the Secure Enclave is released once
    /// no handle references it. Any ciphertext produced before this call
    /// becomes permanently undecryptable.
    ///
    /// Idempotent: succeeds silently if no handle is currently stored.
    ///
    /// - Throws: ``Failure/keychainError(_:)`` if the deletion fails for any
    ///   reason other than the item being absent.
    private func deleteEncryptionKey() throws {
        let status = SecItemDelete(baseQuery as CFDictionary)
        switch status {
        case errSecSuccess, errSecItemNotFound:
            return
        default:
            throw Failure.keychainError(status)
        }
    }
}
